[package]
name = "rfr-subscriber"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [] }

rfr = { version = "0.0.1", path = "../rfr" }

[dev-dependencies]
tokio = { version = "1.38", features = ["full", "tracing"] }
